[package]
name = "headcrab"
version = "0.1.11-rc.1"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "headcrab"

[dependencies]
axum = { version = "0.6.20", features = ["ws"] }
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
hyper = "0.14.27"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tower-http = { version = "0.4.4", features = ["cors"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }

[dev-dependencies]
futures-util = "0.3.28"
reqwest = { version = "0.11.20", features = ["json"] }
tokio-tungstenite = "0.20.1"
