name: Conventional Commit Checker 

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  check-for-cc:
    runs-on: self-hosted
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
