name: Setup Rust
description: Setups the Rust toolchain

inputs:
  version:
    description: The Rust version to use
    required: true

runs:
  using: composite
  steps:
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@dc6353516c68da0f06325f42ad880f76a5e77ec9
      with:
        toolchain: ${{ inputs.version }}
        components: rustfmt,clippy

    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@f7a52f691454d93c6ce0dff6666a5cb399b8d06e

    - name: Cargo Format
      run: cargo fmt --all --check

    - name: Cargo Clippy
      run: cargo clippy -- -D warnings

    - name: Cargo Test
      run: cargo test --all-features