name: Service -> Deploy
description: Deploys the service

inputs:
  image-name:
    description: The service Docker image name
    required: true

runs:
  using: composite
  steps:
    - name: Set the Service Docker image to deploy in k8s.yaml
      shell: bash
      run: sed -i -E "s#headcrab_image#${{ inputs.image-name }}#g" k8s.yaml
      
    - name: Deploy
      if: github.ref_name == 'main'
      shell: bash
      run: |
        diff=`microk8s kubectl apply -f k8s.yaml >> 
        microk8s kubectl rollout status deployment/headcrab-deployment --watch=true --timeout=60s

    - name: Deploy
      if: github.ref_name != 'main'
      id: diff
      shell: bash
      run: |
        diff=`microk8s kubectl diff -f k8s.yaml`
        echo "value=$diff" >> "$GITHUB_OUTPUT"

    - name: Comment diff
      if: github.ref_name != 'main'
      uses: marocchino/sticky-pull-request-comment@5ec44f8ee5ecf07ea2e7410866738fb7890eb756
      with:
        message: |
          ## kubectl diff 
          <details>
            <summary>
              Show diff
            </summary>
            ```diff
            ${{ steps.diff.outputs.value }}
            ```
          </details>
