name: Service -> Deploy
description: Deploys the service

inputs:
  image-name:
    description: The service Docker image name
    required: true
  deploy:
    description: If the service should be deployed or not

runs:
  using: composite
  steps:
    - name: Set version to deploy in k8s.yaml
      run: sed -i -E "s#headcrab_image#${{ inputs.image-name }}#g" k8s.yaml
      
    - name: Deploy
      if: inputs.deploy
      run: |
        microk8s kubectl apply -f k8s.yaml
        microk8s kubectl rollout status deployment/headcrab-deployment --watch=true --timeout=60s
