name: Infrastructure -> Test
description: Tests the infrastructure

inputs:
  image-name:
    description: The service Docker image name
    required: true

runs:
  using: composite
  steps:
    - name: Set the Service Docker image to deploy in k8s.yaml
      shell: bash
      run: sed -i -E "s#headcrab_image#${{ inputs.image-name }}#g" k8s.yaml

    - name: Kubectl diff
      id: diff
      # The diff command returns an error code when there are changes, without the {0} the whole step is marked as failed
      shell: bash {0}
      run: |
        diff=`microk8s kubectl diff -f k8s.yaml`
        echo "$diff"
        echo "value=$diff" >> "$GITHUB_OUTPUT"

    - name: Comment diff
      if: false
      #if: github.ref_name != 'main'
      uses: thollander/actions-comment-pull-request@bc14ce351a6a25022a490f2be0570c700083a7fe
      with:
        message: |
          ## kubectl diff 
          <details>
            <summary>
              Show diff
            </summary>
            ```diff
            ${{ steps.diff.outputs.value }}
            ```
          </details>
