name: Infrastructure -> Test
description: Tests the infrastructure

inputs:
  image-name:
    description: The service Docker image name
    required: true

runs:
  using: composite
  steps:
    - name: Set the Service Docker image to deploy in k8s.yaml
      shell: bash
      run: sed -i -E "s#headcrab_image#${{ inputs.image-name }}#g" k8s.yaml

    - name: Kubectl diff
      # The diff command returns an error code when there are changes, without the {0} the whole step is marked as failed
      shell: bash {0}
      run: |
        diff=`microk8s kubectl diff -f k8s.yaml`
        echo $diff
        {
          echo 'KUBECTL_DIFF<<EOF'
          echo "$diff"
          echo EOF
        } >> "$GITHUB_ENV"

    - name: Comment diff
      if: github.ref_name != 'main'
      uses: marocchino/sticky-pull-request-comment@5ec44f8ee5ecf07ea2e7410866738fb7890eb756
      with:
        message: |
          ## kubectl diff 
          <details>
            <summary>Show diff</summary>

            ```diff
            ${{ env.KUBECTL_DIFF }}
            ```

          </details>
