name: Rust
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true    

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo Test
        run: cargo test --all-features
    
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo Format
        run: cargo fmt --all --check

  linter:
    name: Linter Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo Clippy
        run: cargo clippy -- -D warnings

  build:
    name: Build and deploy
    if: github.ref == 'refs/heads/main'
    needs: [test, format, linter]
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --tag localhost:32000/headcrab:0.0.1
      - name: Push the Docker image to microk8s's registry
        run: docker push localhost:32000/headcrab:0.0.1
      - name: Deploy
        run: microk8s kubectl apply -f k8s.yaml
